### ISSUE TITLE
Compiled size bigger than with ember-precompile

### ISSUE THREAD

**Issue by ifeltsweet** [yaymukund/grunt-ember-handlebars#2]
I assume this is because it uses headless-ember.js while ember-precompile uses handlebars.js in the process.

**Comment by yaymukund** [comment]
I compared a simple file that I compiled using both libraries. My _guess_ is that ember-precompile doesn't support [the helperMissing feature added by Ember](https://github.com/emberjs/ember.js/blob/a2fee026a5e38522b4ec8e858d13c4c4a825be8a/packages/ember-handlebars/lib/ext.js#L243-266).

I'm not sure why this is. It could be a different Ember version, because it doesn't go through headless-ember.js, or something else entirely.

**Comment by yaymukund** [comment]
Going to close this since it doesn't seem to be going anywhere. Please open another issue if you discover anything else :D Thanks!
